name: PHP CodeSniffer
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, pdo_mysql
      - name: Install PHPCS
        run: composer install --no-interaction --prefer-dist
      - name: Run PHPCS
        run: vendor/bin/phpcs --standard=PSR12 app
      - name: Check PHPCS
        run: vendor/bin/phpcs --standard=PSR12 app --report=summary || echo '::set-output name=check_failed::true'
      - name: Check failed
        run: |
          if [ "${{ steps.check.outputs.check_failed }}" == "true" ]; then
            exit 1
          fi
